defaults:
  - data: mdsprites
  - model: video
  - _self_

project: "mdsprites"
name: "default"
seed: 0
wandb_entity: null
log_img_freq: 1000
ckpt_path: null
tf32: False
compile: False
cudnn_benchmark: True
eval_only: False
batch_size: 64

opt:
  lr: 4e-4
  epochs: 530
  n_gpus: 1
  grad_clip: 0.1
  track_grad_norm: -1
  use_lr_scheduler: True
