defaults:
  - data: mdsprites
  - model: image
  - _self_

project: "mdsprites"
name: "default"
seed: 0
wandb_entity: null
log_img_freq: 1000
ckpt_path: null
tf32: False
compile: False
cudnn_benchmark: True
eval_only: False
batch_size: 64

trainer:
  max_epochs: 530
  devices: 1
  accelerator: auto
  gradient_clip_val: 0.1
  gradient_clip_algorithm: norm
  inference_mode: False

opt:
  lr: 4e-4
  use_lr_scheduler: True
